### ISSUE TITLE
saving a bridge array  gives INVALID_INSTANCE

### ISSUE THREAD

**Issue by mcolosimo-p4** [Paradigm4/bridge#11]
Saving a bridge array out using SciDB's save:

```bash
iquery -aq "xsave( filter( apply( build( <v:int64>[i=0:9:0:5; j=10:19:0:5], j + i ), w, double(v*v) ), i >= 5 and w % 2 = 0 ), 'file:///tmp/bridge/bar')"
iquery -aq "save(xinput('file:///tmp/bridge/bar'), '/tmp/bridge/bar_out.tsv',  -2, 'tsv+:l')"
```

results in this error:

> SystemException in file: include/array/ArrayDistribution.h function: LocalArrayDistribution line: 548 instance: s0-i0 (0)
Error id: scidb::scidb::SCIDB_SE_INTERNAL::scidb::SCIDB_LE_ASSERTION_FAILED
Error description: Internal SciDB error. Assertion '_localInstance != INVALID_INSTANCE' failed at /builddir/build/BUILD/paradigm4-19.11-6/include/array/ArrayDistribution.h:548 (Invalid local instance).

This does work:

```bash
iquery -aq "save(_sg( xinput('file:///tmp/bridge/bar'), 1), '/tmp/bridge/bar_out.tsv',  -2, 'tsv+:l')"
```

**Comment by rvernica** [comment]
@apoliakov would this be because I'm not setting the array distribution correctly in `xinput`?

**Comment by apoliakov** [comment]
@rvernica you should check against what the build() operator does. See if Marc's problem reproduces with `build`. If this bug happens with build - it's a deeper scidb bug. If it does not - then you should be able to alter xinput to do the same thing as build.

**Comment by rvernica** [comment]
Shorter repro:
```
> xsave(build(<v:int64>[i=0:1], i), 'file:///tmp/foo')
> save(xinput('file:///tmp/foo'), '/tmp/foo.out')
{chunk_no,dest_instance_id,source_instance_id} val
SystemException in file: include/array/ArrayDistribution.h function: LocalArrayDistribution line: 548 instance: s0-i0 (0)
Error id: scidb::scidb::SCIDB_SE_INTERNAL::scidb::SCIDB_LE_ASSERTION_FAILED
Error description: Internal SciDB error. Assertion '_localInstance != INVALID_INSTANCE' failed at /builddir/build/BUILD/paradigm4-19.11-6/include/array/ArrayDistribution.h:548 (Invalid local instance).
```
