### ISSUE TITLE
Support for Server Side Encryption for S3

### ISSUE THREAD

**Issue by mpeterson-p4** [Paradigm4/bridge#2]
Some customers require uploads to S3 w/ server-side encryption. A quick fix for a specific customer was made by editing 

https://github.com/Paradigm4/bridge/blob/252ac395089f4027fa3e83665b20a91825e5f745/src/S3Driver.cpp#L237

Here, we just added:

```{c++}
request.SetServerSideEncryption(AWS::S3::Model::ServerSideEncryption::AES256)
```
And compiled a new version of the plugin. It would be better to have this as an option to xsave() if we're using S3.

**Comment by rvernica** [comment]
`S3Driver` does the following types of requests to S3:
* `GetObjectRequest` in `init` and `_getRequest`
* `ListObjectsRequest` in `count`
* `PutObjectRequest` in `_putRequest`

Do all these `*ObjectRequest` calls need the server-side encryption flag?

**Comment by mpeterson-p4** [comment]
We only need it for the PutObjectRequest - all of the reads work without adding the SSE flag at the CLI (and with the existing plugin)

**Comment by rvernica** [comment]
Now you can do `xsave(..., s3_sse:'AES256')`

By default, no server-side encryption algorithm is used, i.e., `s3_sse:'NOT_SET'`. Accepted values are `NOT_SET`, `AES256`, and `aws:kms`.
