### ISSUE TITLE
THROW_NOT_OK macro gives wrong number of args to SCIDB_LE_ILLEGAL_OP exception

### ISSUE THREAD

**Issue by mjl-p4** [Paradigm4/bridge#38]
One of the systemic problems with our (P4's) testing pipeline is that CS plugins are only tested with RelWithDebInfo builds of SciDB, which have assertions disabled.  While running my Valgrind build of 22.5 (assertions enabled!), encountered an assertion failure in a templatized `scidb::Exception::operator<<()` method caused by giving too many `<<` arguments:

    #3  0x000000001007a252 in __assert_fail () from /lib64/libc.so.6
    #4  0x00000000021d6c07 in scidb::SystemException::operator<< <char [2]> (
        this=0x1bfc63d0, param=...) at /home/mjl/Sandboxes/Leela/scidb/include/system/Exceptions.h:367
    #5  0x0000000018781fc5 in scidb::ArrowReader::readObject (
        this=this@entry=0x1830a480, name="chunks/c_0", reuse=reuse@entry=false, 
        arrowBatch=std::shared_ptr<arrow::RecordBatch> (empty) = {...})
       at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/basic_string.h:5195
    #6  0x00000000187ba2b7 in scidb::XCache::get (this=0x1830a480, 
        firstPos=std::vector of length 1, capacity 1 = {...}, 
        lastPos=std::vector of length 1, capacity 1 = {...}) at XArray.cpp:86
 
And:

    (gdb) p what
    $3 = "boost::too_many_args: format-string referred to fewer arguments than were passed"
    (gdb) p *this
    $4 = {<scidb::Exception> = {<std::exception> = {<No data fields>}, 
    ...stuff deleted...
	_file = "XIndex.cpp", _function = "readObject", _line = 107, 
	_errors_namespace = "scidb", _short_error_code = 14, 
	_long_error_code = 26, 
	_stringified_short_error_code = "SCIDB_SE_EXECUTION", 
	_stringified_long_error_code = "SCIDB_LE_ILLEGAL_OPERATION", _query_id = {
	  _coordinatorId = 18446744073709551615, _id = 0}, _inst_id = 45, _memo = {
	  content = 0x0}}, <No data fields>}

The solution is that, in the `THROW_NOT_OK()` macro in Driver.h, the SCIDB_LE_ILLEGAL_OPERATION exception should only receive one `<<` argument.  Ideally, double-check the arg counts when throwing other `SYSTEM_EXCEPTION` or `USER_EXCEPTION` objects.

**Comment by rvernica** [comment]
Fixed that occurrence and one more. I identified all possible occurrences using:
```
grep --include='*.cpp' --include="*.h" --after-context=3 --line-number --recursive 'throw ' | grep "<<"
```
