### ISSUE TITLE
scidbbridge R - coercion to 'logical(1)'

### ISSUE THREAD

**Issue by mcolosimo-p4** [Paradigm4/bridge#80]
R4.2.2 generates:

```R
Warning messages:
1: In !is.na(start) && v < start :
  'length(x) = 43500 > 1' in coercion to 'logical(1)'
2: In !is.na(end) && v > end :
  'length(x) = 43500 > 1' in coercion to 'logical(1)'
```

See [array.R#L474](https://github.com/Paradigm4/bridge/blob/696d2ea60d0ee1d699a662599c5d49ffc9327c76/r_pkg/scidbbridge/R/array.R#L474)

R4.3 might generate an Error.

**Comment by mpeterson-p4** [comment]
I think this is a duplicate of #78

**Comment by mcolosimo-p4** [comment]
Yeah it is. Should have read it closer.

Duplicate of #78

**Comment by mcolosimo-p4** [comment]
Duplicate of #78
